site_name: "PipelineTCU"

repo_name: "04_PipelineTCU"
repo_url: "https://github.com/ResidenciaTICBrisa/04_PipelineTCU"

theme:
  name: "material"
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.pat
    - navigation.sections
    - navigation.expand
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  
  font:
    text: Roboto
    code: Roboto Mono

  language: "pt"
  logo: "assets/PipelineTCU.png"
  favicon: "assets/PipelineTCU.png"
  palette:
    primary: "#fff"
    accent: "#0B4D9B"


extra_css:
  - stylesheets/styles.css

nav:
  - Home: index.md
  - Cronograma Geral: cronograma/cronograma.md
  - Roadmap: cronograma/roadmap.md
  - Análise:
    - Projetos Similares: analise/projetos_similares.md 
    - PNE 2050: analise/pne_2050/pne_2050.md
    - IRENA, IEA e NREL: analise/IRENA_IEA_NREL/irena_iea_nrel.md
  - Modelagem:
    - Modelagem Ágil:
      - Backlog do Produto: modelagem/agil/backlog.md
    - Requisitos: modelagem/requisitos.md
    - Protótipo: modelagem/prototipo.md
    - Arquitetura: modelagem/arquitetura.md
  - Fonte de dados: fonte_dados/fonte_dados.md  
  - Gráficos : dashboards/dashboards.md
  - Comunicação:
    - Rituais da Equipe: comunicacao/documentacao_sprints/rituais_da_equipe.md
    - Documentação das Sprints: 
      - Etapa 1: comunicacao/documentacao_sprints/etapa1/etapa1.md
      - Etapa 2: comunicacao/documentacao_sprints/etapa2/etapa2.md
    - Relatorio de Reuniões:
      - Reunião 1: 
        - Reunião de apresentação: comunicacao/reunioes/reuniao1/reuniao.md
      - Reunião 2: 
        - Reunião regras de negócio: comunicacao/reunioes/reuniao2/reuniao.md
        - Acompanhamento projeto: comunicacao/reunioes/reuniao2/acompanhamento.md
      - Reunião 3:
        - Reunião: comunicacao/reunioes/reuniao3/reuniao.md
      - Reunião 4:
        - Reunião: comunicacao/reunioes/reuniao4/reuniao.md      
      - Reunião 5:
        - Reunião: comunicacao/reunioes/reuniao5/reuniao.md   
      - Reunião 6:
        - Reunião: comunicacao/reunioes/reuniao6/reuniao.md
      - Reunião 7:
        - Reunião: comunicacao/reunioes/reuniao7/reuniao.md
    


plugins:
  - search